# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direlegislativo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
