# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direlegislativo', '0004_person_lastname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelMap',
        ),
    ]
