# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipfile', models.FileField(upload_to=b'/var/www/csoapi/static/files/')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('instagram_user', models.IntegerField(null=True)),
            ],
        ),
    ]
