# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liberacion', '0003_auto_20170112_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesforcebackup',
            old_name='appname',
            new_name='app_name',
        ),
    ]
